//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoService.DBInstance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int id { get; set; }
        public string Model { get; set; }
        public string VIN { get; set; }
        public string Engine { get; set; }
        public string Body { get; set; }//кузов
        public string Chassis { get; set; }//шасси
        public Nullable<System.DateTime> Year_Issue { get; set; }//год выпуска
        public Nullable<int> Mileage { get; set; } //пробег
        public int id_Client { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
