//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoService.DBInstance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Date_Coming { get; set; }
        public Nullable<System.DateTime> Date_Consumption { get; set; }
        public Nullable<int> id_Detail { get; set; }
        public Nullable<int> id_Check { get; set; }
        public string Type_Operation { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Detail Detail { get; set; }
    }
}
